search_methods:
 # - method: constant_level
 #   number_of_levels: 5
 # - method: increasing_levels
 #   expected_number_of_iterations: [5,10,15]
 #   number_of_levels: 5  
 #   start_level: 0.0
 #   end_level: 1.0
 # - method: bestNcontinued
 #   number_of_levels: 3
 #   number_of_best: 3
  - method: exhaustive
    number_of_levels: 5
    number_of_changes: 4
savefile: "results-strict-modifications-1000.csv"
abcd_input: "results_1000_he.txt"
dataset_short_name: "abcdh1000"
hmod_type: "strict"
change_mode: "modifications"   
after_changes: 350
community_factor: 2.3
verbosity: false
#random_seeds: [1]
random_seeds: [123,4546,9090,15612,891]
delta_iteration: 0.00001  #epsilon?
delta_phase: 0.00001
